sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t kpkp00014/vsc-test-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true kpkp00014/vsc-test-app npm run test

after_success:
  - echo "start Creating an image with dockerfile"
  - docker build -t kpkp00014/vsc-frontend ./frontend
  - docker build -t kpkp00014/vsc-backend ./backend
  - docker build -t kpkp00014/vsc-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push kpkp00014/vsc-frontend
  - docker push kpkp00014/vsc-backend
  - docker push kpkp00014/vsc-nginx

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "video-scroll-capture-app"
  env: "VideoScrollCaptureApp-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-398861201433"
  bucket_path: "video-scroll-capture-app"
  on:
    branch: main
  label: "vsc-app"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
