version: "3"
services:
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    deploy:
      resources:
        limits:
          cpus: "0.001"
          memory: 50M
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "5000:80"
    deploy:
      resources:
        limits:
          cpus: "0.001"
          memory: 50M
  backend:
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    volumes:
      - /app/node_modules
      - ./backend:/app
    deploy:
      resources:
        limits:
          cpus: "0.001"
          memory: 50M
