// USER LOADING
export const USER_LOADING_REQUEST = "USER_LOADING_REQUEST";
export const USER_LOADING_SUCCESS = "USER_LOADING_SUCCESS";
export const USER_LOADING_FAILURE = "USER_LOADING_FAILURE";

// CLEAR ERROR
export const CLEAR_ERROR_REQUEST = "CLEAR_ERROR_REQUEST";
export const CLEAR_ERROR_SUCCESS = "CLEAR_ERROR_SUCCESS";
export const CLEAR_ERROR_FAILURE = "CLEAR_ERROR_FAILURE";

// LOGIN REQUEST
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

// REGISTER REQUEST
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

// LOGOUT REQUEST
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

// STORAGE_LOADING REQUEST
export const STORAGE_LOADING_REQUEST = "STORAGE_LOADING_REQUEST";
export const STORAGE_LOADING_SUCCESS = "STORAGE_LOADING_SUCCESS";
export const STORAGE_LOADING_FAILURE = "STORAGE_LOADING_FAILURE";

// FILE_UPLOAD REQUEST
export const FILE_UPLOAD_REQUEST = "FILE_UPLOAD_REQUEST";
export const FILE_UPLOAD_SUCCESS = "FILE_UPLOAD_SUCCESS";
export const FILE_UPLOAD_FAILURE = "FILE_UPLOAD_FAILURE";

// PROJECT_INIT_REQUEST
export const PROJECT_INIT_REQUEST = "PROJECT_INIT_REQUEST";
export const PROJECT_INIT_SUCCESS = "PROJECT_INIT_SUCCESS";
export const PROJECT_INIT_FAILURE = "PROJECT_INIT_FAILURE";

// PROJECT_LIST_REQUEST
export const PROJECT_LIST_REQUEST = "PROJECT_LIST_REQUEST";
export const PROJECT_LIST_SUCCESS = "PROJECT_LIST_SUCCESS";
export const PROJECT_LIST_FAILURE = "PROJECT_LIST_FAILURE";

// PROJECT_SELECT_REQUEST
export const PROJECT_SELECT_REQUEST = "PROJECT_SELECT_REQUEST";
export const PROJECT_SELECT_SUCCESS = "PROJECT_SELECT_SUCCESS";
export const PROJECT_SELECT_FAILURE = "PROJECT_SELECT_FAILURE";

// PROJECT_ITEM_UPLOAD_REQUEST
export const PROJECT_ITEM_UPLOAD_REQUEST = "PROJECT_ITEM_UPLOAD_REQUEST";
export const PROJECT_ITEM_UPLOAD_SUCCESS = "PROJECT_ITEM_UPLOAD_SUCCESS";
export const PROJECT_ITEM_UPLOAD_FAILURE = "PROJECT_ITEM_UPLOAD_FAILURE";

// PROJECT_ITEM_LIST_REQUEST
export const PROJECT_ITEM_LIST_REQUEST = "PROJECT_ITEM_LIST_REQUEST";
export const PROJECT_ITEM_LIST_SUCCESS = "PROJECT_ITEM_LIST_SUCCESS";
export const PROJECT_ITEM_LIST_FAILURE = "PROJECT_ITEM_LIST_FAILURE";

// CURRENT_PROJECT_CLEAR_REQUEST
export const CURRENT_PROJECT_CLEAR_REQUEST = "CURRENT_PROJECT_CLEAR_REQUEST";
export const CURRENT_PROJECT_CLEAR_SUCCESS = "CURRENT_PROJECT_CLEAR_SUCCESS";
export const CURRENT_PROJECT_CLEAR_FAILURE = "CURRENT_PROJECT_CLEAR_FAILURE";

// PROJECT_TERMINATE_REQUEST
export const PROJECT_TERMINATE_REQUEST = "PROJECT_TERMINATE_REQUEST";
export const PROJECT_TERMINATE_SUCCESS = "PROJECT_TERMINATE_SUCCESS";
export const PROJECT_TERMINATE_FAILURE = "PROJECT_TERMINATE_FAILURE";

// PROJECT_EXPORT_REQUEST
export const PROJECT_EXPORT_REQUEST = "PROJECT_EXPORT_REQUEST";
export const PROJECT_EXPORT_SUCCESS = "PROJECT_EXPORT_SUCCESS";
export const PROJECT_EXPORT_FAILURE = "PROJECT_EXPORT_FAILURE";

// STORAGE_IMAGE_DELETE_REQUEST
export const STORAGE_IMAGE_DELETE_REQUEST = "STORAGE_IMAGE_DELETE_REQUEST";
export const STORAGE_IMAGE_DELETE_SUCCESS = "STORAGE_IMAGE_DELETE_SUCCESS";
export const STORAGE_IMAGE_DELETE_FAILURE = "STORAGE_IMAGE_DELETE_FAILURE";

// PROJECT_ITEM_DELETE_REQUEST
export const PROJECT_ITEM_DELETE_REQUEST = "PROJECT_ITEM_DELETE_REQUEST";
export const PROJECT_ITEM_DELETE_SUCCESS = "PROJECT_ITEM_DELETE_SUCCESS";
export const PROJECT_ITEM_DELETE_FAILURE = "PROJECT_ITEM_DELETE_FAILURE";
